curl 
--request DELETE
--url http://localhost:2001/contractPayment/64f979654920d3345221bf2f
--header 'token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg0YTU0NDViM2Q4NGNmZTQ2YTliMzAiLCJmaXJzdG5hbWUiOiLZhdit2LPZhiIsImxhc3RuYW1lIjoi2YXYrdmF2K_bjCIsInVzZXJuYW1lIjoibW9oc2VuIiwicGFzc3dvcmQiOiJ4YWQiLCJpc0FjdGl2ZSI6ZmFsc2UsImlzQWRkQ29udHJhY3QiOnRydWUsImlzQ29udHJhY3RNYW5hZ2VyIjpmYWxzZSwiaXNDb250cmFjdFBheW1lbnRNYW5hZ2VyIjpmYWxzZSwiaXNDb250cmFjdFJldml3ZXIiOnRydWUsImlzQ3VzdG9tZXJNYW5hZ2VyIjpmYWxzZSwiaXNVc2VyTWFuYWdlciI6dHJ1ZSwiaWF0IjoxNjkzOTI1NDY4fQ.w6ANlvjLONsMWYPm3l6X-4gFBTv1I425uN7kYLHAh3U'